
<?php	
/**
 * Generated By IN.Cms @ 1416514746
 * 
 * Contains Language Strings for application names.
 * Do not erase this file.
 */
$l['apptitles_insblog_title'] = "IN.Blog";
$l['apptitles_dynamicradio_title'] = "DynamicRadio";
$l['apptitles_instalk_title'] = "IN.Talk";
?>